repositories:
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts

releases:
  - name: prometheus
    namespace: monitoring
    chart: prometheus-community/prometheus
    values:
      - prometheus.yaml
  - name: grafana
    namespace: monitoring
    chart: grafana/grafana
    values:
      - grafana.yaml